alias lss="ls -lhaG"
alias gs="git status"
alias gp="git pull"
alias gf="git fetch"
alias gd="git difftool --dir-diff"
alias gg="git grep -I -n -C2"
alias glo="git log --oneline"
alias glf="git log --graph --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%an%C(reset)%C(bold yellow)%d%C(reset) %C(dim white)- %s%C(reset)' --all"
alias glome="git log --author=\"Rouslan Grabar\""
alias agw="ag -G \"\\.(xml|vm|js)\""
alias rgf="rg --files | rg"
#alias ssh-qa0="ssh rouslan.grabar@cwh.local@10.30.0.119"
#alias ssh-qa1="ssh rouslan.grabar@cwh.local@10.30.1.134"
#alias ssh-prod0="ssh rouslan.grabar@cwh.local@10.30.5.200"
#alias ssh-prod1="ssh rouslan.grabar@cwh.local@10.30.6.241"


